/*------------------------------------------------------------------------------
  Copyright (c) Foxfire Technologies (India) Ltd.  All rights reserved

  Revision History:

  Date        Person  Comments

  2022/10/04  LAC     pr_Imports_OrderHeaders_LoadData/Addresses, pr_Imports_AddOrUpdateAddresses: Added ShipToContactPerson field (BK-941)
  2022/01/20  OK      pr_Imports_OrderHeaders_LoadData: Included missing address fields for ShipTo, SoldTo, return, Mark for and BillTo (BK-742)
  2022/02/10  RKC     pr_Imports_OrderHeaders_LoadData: Removed the Duplicate column in the insert statement (BK-750)
  2022/01/27  OK      pr_Imports_OrderHeaders_LoadData: Included missing address fields for ShipTo, SoldTo, return, Mark for and BillTo (BK-742)
                      pr_Imports_OrderHeaders_LoadData, pr_Imports_OrderHeaders_Validate: Made changes to import the OH & OD through ##Tables (CIMSV3-1604)
------------------------------------------------------------------------------*/

Go

if object_id('dbo.pr_Imports_OrderHeaders_LoadData') is not null
  drop Procedure pr_Imports_OrderHeaders_LoadData;
Go
/*------------------------------------------------------------------------------
  Proc pr_Imports_OrderHeaders_LoadData: Loads the data from ##OrderHeadersImport
   or @xmlData or @documentHandle into #OrderHeadersImport for final processing

  Usage: Create #OrderHeadersImport and call this proc with @xmlData, @documentHandle
         or fill in ##OrderHeadersImport and invoke this proc

  #OrderHeadersImport: TOrderHeadersImportType
------------------------------------------------------------------------------*/
Create Procedure pr_Imports_OrderHeaders_LoadData
  (@xmlData                   Xml             = null,
   @documentHandle            TInteger        = null,
   @InterfaceLogId            TRecordId       = null,
   @Action                    TFlag           = null,
   @PickTicket                TPickTicket     = null,
   @SalesOrder                TSalesOrder     = null,
   @OrderType                 TOrderType      = null,
   @ReceiptNumber             TReceiptNumber  = null,
   @OrderDate                 TDateTime       = null,
   @DesiredShipDate           TDateTime       = null,
   @CancelDate                TDateTime       = null,
   @Priority                  TPriority       = null,
   @SoldToId                  TCustomerId     = null,
   @SoldToName                TName           = null,
   @SoldToAddressLine1        TAddressLine    = null,
   @SoldToAddressLine2        TAddressLine    = null,
   @SoldToCity                TCity           = null,
   @SoldToState               TState          = null,
   @SoldToCountry             TCountry        = null,
   @SoldToZip                 TZip            = null,
   @SoldToPhoneNo             TPhoneNo        = null,
   @SoldToEmail               TEmailAddress   = null,
   @SoldToAddressReference1   TReference      = null,
   @SoldToAddressReference2   TReference      = null,
   @ShipToId                  TShipToId       = null,
   @ShipToName                TName           = null,
   @ShipToContactPerson       TName           = null,
   @ShipToAddressLine1        TAddressLine    = null,
   @ShipToAddressLine2        TAddressLine    = null,
   @ShipToAddressLine3        TAddressLine    = null,
   @ShipToCity                TCity           = null,
   @ShipToState               TState          = null,
   @ShipToCountry             TCountry        = null,
   @ShipToZip                 TZip            = null,
   @ShipToPhoneNo             TPhoneNo        = null,
   @ShipCompletePercent       TPercent        = null,
   @ShipToEmail               TEmailAddress   = null,
   @ShipToAddressReference1   TReference      = null,
   @ShipToAddressReference2   TReference      = null,
   @ShipToResidential         TFlag           = null,
   @ReturnAddrId              TReturnAddress  = null,
   @ReturnAddressName         TName           = null,
   @ReturnAddressLine1        TAddressLine    = null,
   @ReturnAddressLine2        TAddressLine    = null,
   @ReturnAddressCity         TCity           = null,
   @ReturnAddressState        TState          = null,
   @ReturnAddressCountry      TCountry        = null,
   @ReturnAddressZip          TZip            = null,
   @ReturnAddressPhoneNo      TPhoneNo        = null,
   @ReturnAddressEmail        TEmailAddress   = null,
   @ReturnAddressReference1   TReference      = null,
   @ReturnAddressReference2   TReference      = null,
   @MarkForAddress            TContactRefId   = null,
   @MarkForAddressName        TName           = null,
   @MarkForAddressLine1       TAddressLine    = null,
   @MarkForAddressLine2       TAddressLine    = null,
   @MarkForAddressCity        TCity           = null,
   @MarkForAddressState       TState          = null,
   @MarkForAddressCountry     TCountry        = null,
   @MarkForAddressZip         TZip            = null,
   @MarkForAddressPhoneNo     TPhoneNo        = null,
   @MarkForAddressEmail       TEmailAddress   = null,
   @MarkForAddressReference1  TReference      = null,
   @MarkForAddressReference2  TReference      = null,
   @ShipToStore               TShipToStore    = null,
   @ShipVia                   TShipVia        = null,
   @DeliveryRequirement       TDescription    = null,
   @CarrierOptions            TDescription    = null,
   @ShipFrom                  TShipFrom       = null,
   @CustPO                    TCustPO         = null,
   @Ownership                 TOwnership      = null,
   @SourceSystem              TName           = 'HOST',
   @Account                   TCustomerId     = null,
   @AccountName               TName           = null,
   @HostNumLines              TCount          = null,
   @OrderCategory1            TOrderCategory  = null,
   @OrderCategory2            TOrderCategory  = null,
   @OrderCategory3            TOrderCategory  = null,
   @OrderCategory4            TOrderCategory  = null,
   @OrderCategory5            TOrderCategory  = null,
   @Warehouse                 TWarehouse      = null,
   @TotalTax                  TMoney          = null,
   @TotalShippingCost         TMoney          = null,
   @TotalDiscount             TMoney          = null,
   @TotalSalesAmount          TMoney          = null,
   @FreightCharges            TMoney          = null,
   @FreightTerms              TDescription    = null,
   @BillToAccount             TBillToAccount  = null,
   @BillToAddress             TContactRefId   = null,
   @BillToAddressName         TName           = null,
   @BillToAddressLine1        TAddressLine    = null,
   @BillToAddressLine2        TAddressLine    = null,
   @BillToAddressCity         TCity           = null,
   @BillToAddressState        TState          = null,
   @BillToAddressCountry      TCountry        = null,
   @BillToAddressZip          TZip            = null,
   @BillToAddressPhoneNo      TPhoneNo        = null,
   @BillToAddressEmail        TEmailAddress   = null,
   @BillToAddressReference1   TReference      = null,
   @BillToAddressReference2   TReference      = null,
   @Comments                  TVarchar        = null,
   @UDF1                      TUDF            = null,
   @UDF2                      TUDF            = null,
   @UDF3                      TUDF            = null,
   @UDF4                      TUDF            = null,
   @UDF5                      TUDF            = null,
   @UDF6                      TUDF            = null,
   @UDF7                      TUDF            = null,
   @UDF8                      TUDF            = null,
   @UDF9                      TUDF            = null,
   @UDF10                     TUDF            = null,
   @UDF11                     TUDF            = null,
   @UDF12                     TUDF            = null,
   @UDF13                     TUDF            = null,
   @UDF14                     TUDF            = null,
   @UDF15                     TUDF            = null,
   @UDF16                     TUDF            = null,
   @UDF17                     TUDF            = null,
   @UDF18                     TUDF            = null,
   @UDF19                     TUDF            = null,
   @UDF20                     TUDF            = null,
   @UDF21                     TUDF            = null,
   @UDF22                     TUDF            = null,
   @UDF23                     TUDF            = null,
   @UDF24                     TUDF            = null,
   @UDF25                     TUDF            = null,
   @UDF26                     TUDF            = null,
   @UDF27                     TUDF            = null,
   @UDF28                     TUDF            = null,
   @UDF29                     TUDF            = null,
   @UDF30                     TUDF            = null,
   @BusinessUnit              TBusinessUnit   = null,
   @CreatedDate               TDateTime       = null,
   @ModifiedDate              TDateTime       = null,
   @CreatedBy                 TUserId         = null,
   @ModifiedBy                TUserId         = null,
   @HostRecId         TRecordId               = null,
   @IsDESameServer    TFlag                   = null,
   @RecordId          TRecordId               = null)
as
begin /* pr_Imports_OrderHeaders_LoadData */

  if (@IsDESameServer = 'Y') and (@RecordId is not null)
    insert into #OrderHeadersImport (
      RecordType, RecordAction, PickTicket, SalesOrder, OrderType, HostNumLines,
      OrderDate, NB4Date, DesiredShipDate, CancelDate, DeliveryStart, DeliveryEnd,
      Priority, CustPO, Account, AccountName,
      SoldToId, SoldToName, SoldToAddressLine1, SoldToAddressLine2, SoldToCity, SoldToState, SoldToCountry,
      SoldToZip, SoldToPhoneNo, SoldToEmail, SoldToAddressReference1, SoldToAddressReference2,
      ShipToId, ShipToName, ShipToAddressLine1, ShipToAddressLine2, ShipToAddressLine3, ShipToCity, ShipToState, ShipToCountry,
      ShipToZip, ShipToPhoneNo, ShipToEmail, ShipToAddressReference1, ShipToAddressReference2, ShipToResidential, ShipToContactPerson,
      ReturnAddrId, ReturnAddressName, ReturnAddressLine1, ReturnAddressLine2, ReturnAddressCity, ReturnAddressState, ReturnAddressCountry,
      ReturnAddressZip, ReturnAddressPhoneNo, ReturnAddressEmail, ReturnAddressReference1, ReturnAddressReference2,
      MarkForAddress, MarkForAddressName, MarkForAddressLine1, MarkForAddressLine2, MarkForAddressCity, MarkForAddressState, MarkForAddressCountry,
      MarkForAddressZip, MarkForAddressPhoneNo, MarkForAddressEmail, MarkForAddressReference1, MarkForAddressReference2,
      BillToAddress, BillToAddressName, BillToAddressLine1, BillToAddressLine2, BillToAddressCity, BillToAddressState, BillToAddressCountry,
      BillToAddressZip, BillToAddressPhoneNo, BillToAddressEmail, BillToAddressReference1, BillToAddressReference2,
      ShipFrom, ShipToStore, ShipVia, FreightTerms, BillToAccount, DeliveryRequirement, CarrierOptions, ShipCompletePercent,
      OrderCategory1, OrderCategory2, OrderCategory3, OrderCategory4, OrderCategory5,
      Ownership, Warehouse,
      ReceiptNumber, Comments, CartonGroup, WaveGroup,
      TotalTax, TotalShippingCost, TotalDiscount, TotalSalesAmount, FreightCharges,
      OH_UDF1,  OH_UDF2,  OH_UDF3,  OH_UDF4,  OH_UDF5,  OH_UDF6,  OH_UDF7,  OH_UDF8,  OH_UDF9,  OH_UDF10,
      OH_UDF11, OH_UDF12, OH_UDF13, OH_UDF14, OH_UDF15, OH_UDF16, OH_UDF17, OH_UDF18, OH_UDF19, OH_UDF20,
      OH_UDF21, OH_UDF22, OH_UDF23, OH_UDF24, OH_UDF25, OH_UDF26, OH_UDF27, OH_UDF28, OH_UDF29, OH_UDF30,
      SourceSystem, BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy,
      Status, HostRecId)
    select RecordType, RecordAction, PickTicket, SalesOrder, OrderType, HostNumLines,
      OrderDate, NB4Date, DesiredShipDate, CancelDate, DeliveryStart, DeliveryEnd,
      Priority, CustPO, Account, AccountName,
      SoldToId, SoldToName, SoldToAddressLine1, SoldToAddressLine2, SoldToCity, SoldToState, SoldToCountry,
      SoldToZip, SoldToPhoneNo, SoldToEmail, SoldToAddressReference1, SoldToAddressReference2,
      ShipToId, ShipToName, ShipToAddressLine1, ShipToAddressLine2, ShipToAddressLine3, ShipToCity, ShipToState, ShipToCountry,
      ShipToZip, ShipToPhoneNo, ShipToEmail, ShipToAddressReference1, ShipToAddressReference2, ShipToResidential, ShipToContactPerson,
      ReturnAddrId, ReturnAddressName, ReturnAddressLine1, ReturnAddressLine2, ReturnAddressCity, ReturnAddressState, ReturnAddressCountry,
      ReturnAddressZip, ReturnAddressPhoneNo, ReturnAddressEmail, ReturnAddressReference1, ReturnAddressReference2,
      MarkForAddress, MarkForAddressName, MarkForAddressLine1, MarkForAddressLine2, MarkForAddressCity, MarkForAddressState, MarkForAddressCountry,
      MarkForAddressZip, MarkForAddressPhoneNo, MarkForAddressEmail, MarkForAddressReference1, MarkForAddressReference2,
      BillToAddress, BillToAddressName, BillToAddressLine1, BillToAddressLine2, BillToAddressCity, BillToAddressState, BillToAddressCountry,
      BillToAddressZip, BillToAddressPhoneNo, BillToAddressEmail, BillToAddressReference1, BillToAddressReference2,
      ShipFrom, ShipToStore, ShipVia, FreightTerms, BillToAccount, DeliveryRequirement, CarrierOptions, ShipCompletePercent,
      OrderCategory1, OrderCategory2, OrderCategory3, OrderCategory4, OrderCategory5,
      Ownership, Warehouse,
      ReceiptNumber, Comments, CartonGroup, WaveGroup,
      TotalTax, TotalShippingCost, TotalDiscount, TotalSalesAmount, FreightCharges,
      OH_UDF1,  OH_UDF2,  OH_UDF3,  OH_UDF4,  OH_UDF5,  OH_UDF6,  OH_UDF7,  OH_UDF8,  OH_UDF9,  OH_UDF10,
      OH_UDF11, OH_UDF12, OH_UDF13, OH_UDF14, OH_UDF15, OH_UDF16, OH_UDF17, OH_UDF18, OH_UDF19, OH_UDF20,
      OH_UDF21, OH_UDF22, OH_UDF23, OH_UDF24, OH_UDF25, OH_UDF26, OH_UDF27, OH_UDF28, OH_UDF29, OH_UDF30,
      SourceSystem, BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy,
      Status, RecordId
    from ##ImportOrderHeaders
    where (RecordId = @RecordId)
  else
  if (@IsDESameServer = 'Y')
   insert into #OrderHeadersImport (
      RecordType, RecordAction, PickTicket, SalesOrder, OrderType, HostNumLines,
      OrderDate, NB4Date, DesiredShipDate, CancelDate, DeliveryStart, DeliveryEnd,
      Priority, CustPO, Account, AccountName,
      SoldToId, SoldToName, SoldToAddressLine1, SoldToAddressLine2, SoldToCity, SoldToState, SoldToCountry,
      SoldToZip, SoldToPhoneNo, SoldToEmail, SoldToAddressReference1, SoldToAddressReference2,
      ShipToId, ShipToName, ShipToAddressLine1, ShipToAddressLine2, ShipToAddressLine3, ShipToCity, ShipToState, ShipToCountry,
      ShipToZip, ShipToPhoneNo, ShipToEmail, ShipToAddressReference1, ShipToAddressReference2, ShipToResidential, ShipToContactPerson,
      ReturnAddrId, ReturnAddressName, ReturnAddressLine1, ReturnAddressLine2, ReturnAddressCity, ReturnAddressState, ReturnAddressCountry,
      ReturnAddressZip, ReturnAddressPhoneNo, ReturnAddressEmail, ReturnAddressReference1, ReturnAddressReference2,
      MarkForAddress, MarkForAddressName, MarkForAddressLine1, MarkForAddressLine2, MarkForAddressCity, MarkForAddressState, MarkForAddressCountry,
      MarkForAddressZip, MarkForAddressPhoneNo, MarkForAddressEmail, MarkForAddressReference1, MarkForAddressReference2,
      BillToAddress, BillToAddressName, BillToAddressLine1, BillToAddressLine2, BillToAddressCity, BillToAddressState, BillToAddressCountry,
      BillToAddressZip, BillToAddressPhoneNo, BillToAddressEmail, BillToAddressReference1, BillToAddressReference2,
      ShipFrom, ShipToStore, ShipVia, FreightTerms, BillToAccount, DeliveryRequirement, CarrierOptions, ShipCompletePercent,
      OrderCategory1, OrderCategory2, OrderCategory3, OrderCategory4, OrderCategory5,
      Ownership, Warehouse,
      ReceiptNumber, Comments, CartonGroup, WaveGroup,
      TotalTax, TotalShippingCost, TotalDiscount, TotalSalesAmount, FreightCharges,
      OH_UDF1,  OH_UDF2,  OH_UDF3,  OH_UDF4,  OH_UDF5,  OH_UDF6,  OH_UDF7,  OH_UDF8,  OH_UDF9,  OH_UDF10,
      OH_UDF11, OH_UDF12, OH_UDF13, OH_UDF14, OH_UDF15, OH_UDF16, OH_UDF17, OH_UDF18, OH_UDF19, OH_UDF20,
      OH_UDF21, OH_UDF22, OH_UDF23, OH_UDF24, OH_UDF25, OH_UDF26, OH_UDF27, OH_UDF28, OH_UDF29, OH_UDF30,
      SourceSystem, BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy,
      Status, HostRecId)
    select RecordType, RecordAction, PickTicket, SalesOrder, OrderType, HostNumLines,
      OrderDate, NB4Date, DesiredShipDate, CancelDate, DeliveryStart, DeliveryEnd,
      Priority, CustPO, Account, AccountName,
      SoldToId, SoldToName, SoldToAddressLine1, SoldToAddressLine2, SoldToCity, SoldToState, SoldToCountry,
      SoldToZip, SoldToPhoneNo, SoldToEmail, SoldToAddressReference1, SoldToAddressReference2,
      ShipToId, ShipToName, ShipToAddressLine1, ShipToAddressLine2, ShipToAddressLine3, ShipToCity, ShipToState, ShipToCountry,
      ShipToZip, ShipToPhoneNo, ShipToEmail, ShipToAddressReference1, ShipToAddressReference2, ShipToResidential, ShipToContactPerson,
      ReturnAddrId, ReturnAddressName, ReturnAddressLine1, ReturnAddressLine2, ReturnAddressCity, ReturnAddressState, ReturnAddressCountry,
      ReturnAddressZip, ReturnAddressPhoneNo, ReturnAddressEmail, ReturnAddressReference1, ReturnAddressReference2,
      MarkForAddress, MarkForAddressName, MarkForAddressLine1, MarkForAddressLine2, MarkForAddressCity, MarkForAddressState, MarkForAddressCountry,
      MarkForAddressZip, MarkForAddressPhoneNo, MarkForAddressEmail, MarkForAddressReference1, MarkForAddressReference2,
      BillToAddress, BillToAddressName, BillToAddressLine1, BillToAddressLine2, BillToAddressCity, BillToAddressState, BillToAddressCountry,
      BillToAddressZip, BillToAddressPhoneNo, BillToAddressEmail, BillToAddressReference1, BillToAddressReference2,
      ShipFrom, ShipToStore, ShipVia, FreightTerms, BillToAccount, DeliveryRequirement, CarrierOptions, ShipCompletePercent,
      OrderCategory1, OrderCategory2, OrderCategory3, OrderCategory4, OrderCategory5,
      Ownership, Warehouse,
      ReceiptNumber, Comments, CartonGroup, WaveGroup,
      TotalTax, TotalShippingCost, TotalDiscount, TotalSalesAmount, FreightCharges,
      OH_UDF1,  OH_UDF2,  OH_UDF3,  OH_UDF4,  OH_UDF5,  OH_UDF6,  OH_UDF7,  OH_UDF8,  OH_UDF9,  OH_UDF10,
      OH_UDF11, OH_UDF12, OH_UDF13, OH_UDF14, OH_UDF15, OH_UDF16, OH_UDF17, OH_UDF18, OH_UDF19, OH_UDF20,
      OH_UDF21, OH_UDF22, OH_UDF23, OH_UDF24, OH_UDF25, OH_UDF26, OH_UDF27, OH_UDF28, OH_UDF29, OH_UDF30,
      SourceSystem, BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy,
      Status, RecordId
    from ##ImportOrderHeaders
  else
  /* Populate the temp table */
  if (@documentHandle is not null)
    begin
      /* insert into OrderHeaders Imports Table from the xmldata */
      insert into #OrderHeadersImport (
        InputXML,
        RecordType,
        RecordAction,
        PickTicket,
        SalesOrder,
        OrderType,
        ReceiptNumber,
        OrderDate,
        DesiredShipDate,
        CancelDate,
        Priority,
        SoldToId,
        SoldToName,
        SoldToAddressLine1,
        SoldToAddressLine2,
        SoldToCity,
        SoldToState,
        SoldToCountry,
        SoldToZip,
        SoldToPhoneNo,
        SoldToEmail,
        SoldToAddressReference1,
        SoldToAddressReference2,
        ShipToId,
        ShipToName,
        ShipToAddressLine1,
        ShipToAddressLine2,
        ShipToAddressLine3,
        ShipToCity,
        ShipToState,
        ShipToCountry,
        ShipToZip,
        ShipToPhoneNo,
        ShipCompletePercent,
        ShipToEmail,
        ShipToAddressReference1,
        ShipToAddressReference2,
        ShipToResidential,
        ShipToContactPerson,
        ReturnAddrId,
        ReturnAddressName,
        ReturnAddressLine1,
        ReturnAddressLine2,
        ReturnAddressCity,
        ReturnAddressState,
        ReturnAddressCountry,
        ReturnAddressZip,
        ReturnAddressPhoneNo,
        ReturnAddressEmail,
        ReturnAddressReference1,
        ReturnAddressReference2,
        MarkForAddress,
        MarkForAddressName,
        MarkForAddressLine1,
        MarkForAddressLine2,
        MarkForAddressCity,
        MarkForAddressState,
        MarkForAddressCountry,
        MarkForAddressZip,
        MarkForAddressPhoneNo,
        MarkForAddressEmail,
        MarkForAddressReference1,
        MarkForAddressReference2,
        ShipToStore,
        ShipVia,
        DeliveryRequirement,
        CarrierOptions,
        ShipFrom,
        CustPO,
        Ownership,
        SourceSystem,
        Account,
        AccountName,
        HostNumLines,
        OrderCategory1,
        OrderCategory2,
        OrderCategory3,
        OrderCategory4,
        OrderCategory5,
        Warehouse,
        TotalTax,
        TotalShippingCost,
        TotalDiscount,
        TotalSalesAmount,
        FreightCharges,
        FreightTerms,
        BillToAccount,
        BillToAddress,
        BillToAddressName,
        BillToAddressLine1,
        BillToAddressLine2,
        BillToAddressCity,
        BillToAddressState,
        BillToAddressCountry,
        BillToAddressZip,
        BillToAddressPhoneNo,
        BillToAddressEmail,
        BillToAddressReference1,
        BillToAddressReference2,
        Comments,
        OH_UDF1,
        OH_UDF2,
        OH_UDF3,
        OH_UDF4,
        OH_UDF5,
        OH_UDF6,
        OH_UDF7,
        OH_UDF8,
        OH_UDF9,
        OH_UDF10,
        OH_UDF11,
        OH_UDF12,
        OH_UDF13,
        OH_UDF14,
        OH_UDF15,
        OH_UDF16,
        OH_UDF17,
        OH_UDF18,
        OH_UDF19,
        OH_UDF20,
        OH_UDF21,
        OH_UDF22,
        OH_UDF23,
        OH_UDF24,
        OH_UDF25,
        OH_UDF26,
        OH_UDF27,
        OH_UDF28,
        OH_UDF29,
        OH_UDF30,
        BusinessUnit,
        CreatedDate,
        ModifiedDate,
        CreatedBy,
        ModifiedBy,
        HostRecId,
        Status)
      select
        *,
        'O' as Status
      from OPENXML(@documentHandle, '//msg/msgBody/Record[RecordType/text()="OH"]', 2) -- condition forces to read only Records with RecordType OH
      with (InputXML                 nvarchar(max)  '@mp:xmltext', -- Directive to return the xmltext of the record node
            RecordType               TRecordType,
            RecordAction             TAction        'Action',
            PickTicket               TPickTicket,
            SalesOrder               TSalesOrder,
            OrderType                TOrderType,
            ReceiptNumber            TReceiptNumber,
            OrderDate                TDateTime      'OrderDate/text()',       -- returns null when the xml contains only the OrderDate element with no data. Acts as NullIf function
            DesiredShipDate          TDateTime      'DesiredShipDate/text()', -- see OrderDate comments
            CancelDate               TDateTime      'CancelDate/text()',      -- see OrderDate comments
            Priority                 TPriority,
            SoldToId                 TCustomerId,
            SoldToName               TName          'SoldToName/text()',      -- see OrderDate comments
            SoldToAddressLine1       TAddressLine,
            SoldToAddressLine2       TAddressLine,
            SoldToCity               TCity,
            SoldToState              TState,
            SoldToCountry            TCountry,
            SoldToZip                TZip,
            SoldToPhoneNo            TPhoneNo,
            SoldToEmail              TEmailAddress,
            SoldToAddressReference1  TReference,
            SoldToAddressReference2  TReference,
            ShipToId                 TShipToId,
            ShipToName               TName          'ShipToName/text()',      -- see OrderDate comments
            ShipToAddressLine1       TAddressLine,
            ShipToAddressLine2       TAddressLine,
            ShipToAddressLine3       TAddressLine,
            ShipToCity               TCity,
            ShipToState              TState,
            ShipToCountry            TCountry,
            ShipToZip                TZip,
            ShipToPhoneNo            TPhoneNo,
            ShipCompletePercent      TPercent       'ShipCompletePercent/text()',
            ShipToEmail              TEmailAddress,
            ShipToAddressReference1  TReference,
            ShipToAddressReference2  TReference,
            ShipToResidential        TFlag,
            ShipToContactPerson      TName,
            ReturnAddrId             TReturnAddress,
            ReturnAddressName        TName          'ReturnAddressName/text()',-- see OrderDate comments
            ReturnAddressLine1       TAddressLine,
            ReturnAddressLine2       TAddressLine,
            ReturnAddressCity        TCity,
            ReturnAddressState       TState,
            ReturnAddressCountry     TCountry,
            ReturnAddressZip         TZip,
            ReturnAddressPhoneNo     TPhoneNo,
            ReturnAddressEmail       TEmailAddress,
            ReturnAddressReference1  TReference,
            ReturnAddressReference2  TReference,
            MarkForAddress           TContactRefId,
            MarkForAddressName       TName          'MarkForAddressName/text()',-- see OrderDate comments
            MarkForAddressLine1      TAddressLine,
            MarkForAddressLine2      TAddressLine,
            MarkForAddressCity       TCity,
            MarkForAddressState      TState,
            MarkForAddressCountry    TCountry,
            MarkForAddressZip        TZip,
            MarkForAddressPhoneNo    TPhoneNo,
            MarkForAddressEmail      TEmailAddress,
            MarkForAddressReference1 TReference,
            MarkForAddressReference2 TReference,
            ShipToStore              TShipToStore,
            ShipVia                  TShipVia,
            DeliveryRequirement      TDescription,
            CarrierOptions           TDescription,
            ShipFrom                 TShipFrom,
            CustPO                   TCustPO,
            Ownership                TOwnership,
            SourceSystem             TName,
            Account                  TCustomerId,
            AccountName              TName,
            HostNumLines             TCount,
            OrderCategory1           TOrderCategory,
            OrderCategory2           TOrderCategory,
            OrderCategory3           TOrderCategory,
            OrderCategory4           TOrderCategory,
            OrderCategory5           TOrderCategory,
            Warehouse                TWarehouse,
            TotalTax                 TMoney,
            TotalShippingCost        TMoney,
            TotalDiscount            TMoney,
            TotalSalesAmount         TMoney,
            FreightCharges           TMoney,
            FreightTerms             TDescription,
            BillToAccount            TBillToAccount,
            BillToAddress            TContactRefId,
            BillToAddressName        TName         'BillToAddressName/text()',-- see OrderDate comments
            BillToAddressLine1       TAddressLine,
            BillToAddressLine2       TAddressLine,
            BillToAddressCity        TCity,
            BillToAddressState       TState,
            BillToAddressCountry     TCountry,
            BillToAddressZip         TZip,
            BillToAddressPhoneNo     TPhoneNo,
            BillToAddressEmail       TEmailAddress,
            BillToAddressReference1  TReference,
            BillToAddressReference2  TReference,
            Comments                 TVarchar,
            OH_UDF1                  TUDF,
            OH_UDF2                  TUDF,
            OH_UDF3                  TUDF,
            OH_UDF4                  TUDF,
            OH_UDF5                  TUDF,
            OH_UDF6                  TUDF,
            OH_UDF7                  TUDF,
            OH_UDF8                  TUDF,
            OH_UDF9                  TUDF,
            OH_UDF10                 TUDF,
            OH_UDF11                 TUDF,
            OH_UDF12                 TUDF,
            OH_UDF13                 TUDF,
            OH_UDF14                 TUDF,
            OH_UDF15                 TUDF,
            OH_UDF16                 TUDF,
            OH_UDF17                 TUDF,
            OH_UDF18                 TUDF,
            OH_UDF19                 TUDF,
            OH_UDF20                 TUDF,
            OH_UDF21                 TUDF,
            OH_UDF22                 TUDF,
            OH_UDF23                 TUDF,
            OH_UDF24                 TUDF,
            OH_UDF25                 TUDF,
            OH_UDF26                 TUDF,
            OH_UDF27                 TUDF,
            OH_UDF28                 TUDF,
            OH_UDF29                 TUDF,
            OH_UDF30                 TUDF,
            BusinessUnit             TBusinessUnit,
            CreatedDate              TDateTime     'CreatedDate/text()',         -- see OrderDate comments
            ModifiedDate             TDateTime     'ModifiedDate/text()',        -- see OrderDate comments
            CreatedBy                TUserId,
            ModifiedBy               TUserId,
            RecordId                 TRecordId);
    end
  else
    begin
      /* insert into OrderHeadersImport Table */
      insert into #OrderHeadersImport (
        RecordAction, RecordType, PickTicket, SalesOrder,
        OrderType, ReceiptNumber, Status,
        OrderDate, DesiredShipDate, CancelDate, Priority,
        SoldToId, SoldToName, SoldToAddressLine1, SoldToAddressLine2, SoldToCity, SoldToState, SoldToCountry,
        SoldToZip, SoldToPhoneNo, SoldToEmail, SoldToAddressReference1, SoldToAddressReference2,
        ShipToId, ShipToName, ShipToAddressLine1, ShipToAddressLine2, ShipToAddressLine3, ShipToCity, ShipToState, ShipToCountry,
        ShipToZip, ShipToPhoneNo, ShipToEmail, ShipToAddressReference1, ShipToAddressReference2, ShipToResidential, ShipToContactPerson,
        ReturnAddrId, ReturnAddressName, ReturnAddressLine1, ReturnAddressLine2, ReturnAddressCity, ReturnAddressState, ReturnAddressCountry,
        ReturnAddressZip, ReturnAddressPhoneNo, ReturnAddressEmail, ReturnAddressReference1, ReturnAddressReference2,
        MarkForAddress, MarkForAddressName, MarkForAddressLine1, MarkForAddressLine2, MarkForAddressCity, MarkForAddressState,
        MarkForAddressCountry, MarkForAddressZip, MarkForAddressPhoneNo, MarkForAddressEmail, MarkForAddressReference1, MarkForAddressReference2,
        BillToAddress, BillToAddressName, BillToAddressLine1, BillToAddressLine2, BillToAddressCity, BillToAddressState, BillToAddressCountry,
        BillToAddressZip, BillToAddressPhoneNo, BillToAddressEmail, BillToAddressReference1, BillToAddressReference2,
        ShipToStore, ShipVia, DeliveryRequirement, CarrierOptions, ShipFrom, ShipCompletePercent,
        CustPO, Ownership, SourceSystem,
        Account, AccountName, HostNumLines, OrderCategory1,
        OrderCategory2, OrderCategory3,
        OrderCategory4, OrderCategory5, Warehouse,
        TotalTax, TotalShippingCost, TotalDiscount, TotalSalesAmount,
        FreightCharges, FreightTerms, BillToAccount, Comments,
        OH_UDF1, OH_UDF2, OH_UDF3, OH_UDF4, OH_UDF5, OH_UDF6, OH_UDF7, OH_UDF8, OH_UDF9, OH_UDF10,
        OH_UDF11, OH_UDF12, OH_UDF13, OH_UDF14, OH_UDF15, OH_UDF16, OH_UDF17, OH_UDF18, OH_UDF19, OH_UDF20,
        OH_UDF21, OH_UDF22, OH_UDF23, OH_UDF24, OH_UDF25, OH_UDF26, OH_UDF27, OH_UDF28, OH_UDF29, OH_UDF30,
        BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy, HostRecId)
      select
        @Action, 'OH', @PickTicket, @SalesOrder,
        @OrderType, @ReceiptNumber,
        case when (@OrderType in ('RP', 'RU', 'R'/* Replenish Cases, Units, Orders */))
                      then 'N' /* New */ else 'O' /* Downloaded */ end,
        @OrderDate, @DesiredShipDate, @CancelDate, @Priority,
        @SoldToId, @SoldToName, @SoldToAddressLine1, @SoldToAddressLine2, @SoldToCity, @SoldToState, @SoldToCountry,
        @SoldToZip, @SoldToPhoneNo, @SoldToEmail, @SoldToAddressReference1, @SoldToAddressReference2,
        @ShipToId, @ShipToName, @ShipToAddressLine1, @ShipToAddressLine2, @ShipToAddressLine3, @ShipToCity, @ShipToState, @ShipToCountry,
        @ShipToZip, @ShipToPhoneNo, @ShipToEmail, @ShipToAddressReference1, @ShipToAddressReference2, @ShipToResidential, @ShipToContactPerson,
        @ReturnAddrId, @ReturnAddressName, @ReturnAddressLine1, @ReturnAddressLine2, @ReturnAddressCity, @ReturnAddressState, @ReturnAddressCountry,
        @ReturnAddressZip, @ReturnAddressPhoneNo, @ReturnAddressEmail, @ReturnAddressReference1, @ReturnAddressReference2,
        @MarkForAddress, @MarkForAddressName, @MarkForAddressLine1, @MarkForAddressLine2, @MarkForAddressCity, @MarkForAddressState,
        @MarkForAddressCountry, @MarkForAddressZip, @MarkForAddressPhoneNo, @MarkForAddressEmail, @MarkForAddressReference1, @MarkForAddressReference2,
        @BillToAddress, @BillToAddressName, @BillToAddressLine1, @BillToAddressLine2, @BillToAddressCity, @BillToAddressState, @BillToAddressCountry,
        @BillToAddressZip, @BillToAddressPhoneNo, @BillToAddressEmail, @BillToAddressReference1, @BillToAddressReference2,
        @ShipToStore, ltrim(rtrim(@ShipVia)), @DeliveryRequirement, @CarrierOptions, @ShipFrom, coalesce(@ShipCompletePercent, 0),
        @CustPO, @Ownership, @SourceSystem,
        @Account, @AccountName, @HostNumLines, @OrderCategory1,
        @OrderCategory2, @OrderCategory3,
        @OrderCategory4, @OrderCategory5, @Warehouse,
        @TotalTax, @TotalShippingCost, @TotalDiscount, @TotalSalesAmount,
        @FreightCharges, @FreightTerms, @BillToAccount, @Comments,
        @UDF1, @UDF2, @UDF3, @UDF4, @UDF5, @UDF6, @UDF7, @UDF8, @UDF9, @UDF10,
        @UDF11, @UDF12, @UDF13, @UDF14, @UDF15, @UDF16, @UDF17, @UDF18, @UDF19, @UDF20,
        @UDF21, @UDF22, @UDF23, @UDF24, @UDF25, @UDF26, @UDF27, @UDF28, @UDF29, @UDF30,
        @BusinessUnit, @CreatedDate, @ModifiedDate, @CreatedBy, @ModifiedBy, @HostRecId;
    end

end /* pr_Imports_OrderHeaders_LoadData */

Go
