/*------------------------------------------------------------------------------
  Copyright (c) Foxfire Technologies (India) Ltd.  All rights reserved

  Revision History:

  Date        Person  Comments

  2023/02/08  PHK     pr_Imports_SKUs_LoadData: UDF* changed to SKU_UDF* (BK-1012)
------------------------------------------------------------------------------*/

Go

if object_id('dbo.pr_Imports_SKUs_LoadData') is not null
  drop Procedure pr_Imports_SKUs_LoadData;
Go
/*------------------------------------------------------------------------------
  Proc pr_Imports_SKUs_LoadData: Loads the edata from ##ImportSKUs or @xmlData or
    @documentHandle into #ImportSKUs for final processing
------------------------------------------------------------------------------*/
Create Procedure pr_Imports_SKUs_LoadData
  (@xmlData           Xml             = null,
   @documentHandle    TInteger        = null,
   @InterfaceLogId    TRecordId       = null,
   @Action            TFlag           = null,
   @SKU               TSKU            = null,
   @SKU1              TSKU            = null,
   @SKU2              TSKU            = null,
   @SKU3              TSKU            = null,
   @SKU4              TSKU            = null,
   @SKU5              TSKU            = null,
   @Description       TDescription    = null,
   @SKU1Description   TDescription    = null,
   @SKU2Description   TDescription    = null,
   @SKU3Description   TDescription    = null,
   @SKU4Description   TDescription    = null,
   @SKU5Description   TDescription    = null,
   @AlternateSKU      TSKU            = null,
   @Status            TStatus         = null,
   @UoM               TUoM            = null,
   @InnerPacksPerLPN  TInteger        = null,
   @UnitsPerInnerPack TInteger        = null,
   @UnitsPerLPN       TInteger        = null,
   @InnerPackWeight   TFloat          = null,
   @InnerPackLength   TFloat          = null,
   @InnerPackWidth    TFloat          = null,
   @InnerPackHeight   TFloat          = null,
   @InnerPackVolume   TFloat          = null,
   @UnitWeight        TFloat          = null,
   @UnitLength        TFloat          = null,
   @UnitWidth         TFloat          = null,
   @UnitHeight        TFloat          = null,
   @UnitVolume        TFloat          = null,
   @NestingFactor     TFloat          = null,
   @UnitPrice         TFloat          = null,
   @UnitCost          TFloat          = null,
   @PalletTie         TInteger        = null,
   @PalletHigh        TInteger        = null,
   @PickUoM           TFlags          = null,
   @ShipUoM           TFlags          = null,
   @ShipPack          TInteger        = null,
   @IsSortable        TFlags          = null,
   @IsConveyable      TFlags          = null,
   @IsScannable       TFlags          = null,
   @SKUSortOrder      TDescription    = null,
   @Barcode           TBarcode        = null,
   @UPC               TUPC            = null,
   @CaseUPC           TUPC            = null,
   @Brand             TBrand          = null,
   @ProdCategory      TCategory       = null,
   @ProdSubCategory   TCategory       = null,
   @PutawayClass      TCategory       = null,
   @ABCClass          TFlag           = null,
   @ReturnDisposition TOperation      = null,
   @NMFC              TTypeCode       = null,
   @HarmonizedCode    THarmonizedCode = null,
   @Ownership         TOwnership      = null,
   @DefaultCoO        TCoO            = null,
   @UDF1              TUDF            = null,
   @UDF2              TUDF            = null,
   @UDF3              TUDF            = null,
   @UDF4              TUDF            = null,
   @UDF5              TUDF            = null,
   @UDF6              TUDF            = null,
   @UDF7              TUDF            = null,
   @UDF8              TUDF            = null,
   @UDF9              TUDF            = null,
   @UDF10             TUDF            = null,
   @UDF11             TUDF            = null,
   @UDF12             TUDF            = null,
   @UDF13             TUDF            = null,
   @UDF14             TUDF            = null,
   @UDF15             TUDF            = null,
   @UDF16             TUDF            = null,
   @UDF17             TUDF            = null,
   @UDF18             TUDF            = null,
   @UDF19             TUDF            = null,
   @UDF20             TUDF            = null,
   @UDF21             TUDF            = null,
   @UDF22             TUDF            = null,
   @UDF23             TUDF            = null,
   @UDF24             TUDF            = null,
   @UDF25             TUDF            = null,
   @UDF26             TUDF            = null,
   @UDF27             TUDF            = null,
   @UDF28             TUDF            = null,
   @UDF29             TUDF            = null,
   @UDF30             TUDF            = null,
   @SourceSystem      TUDF            = null,
   @BusinessUnit      TBusinessUnit   = null,
   @CreatedDate       TDateTime       = null,
   @ModifiedDate      TDateTime       = null,
   @CreatedBy         TUserId         = null,
   @ModifiedBy        TUserId         = null,
   @HostRecId         TRecordId       = null,
   @IsDESameServer    TFlag           = null,
   @RecordId          TRecordId       = null)
as
  declare @vBusinessUnit           TBusinessUnit,
          @vReturnCode             TInteger,
          @Serialized              TFlag,
          @ttSKUs                  TEntityKeysTable,
          @vParentLogId            TRecordId;

  declare @vSKUPutawayClassUpdate  TString,
          @vSKUPackInfoUpdate      Tstring,
          @vSKUCubeUpdate          TString,
          @vSKUWeightUpdate        TString,
          @vSKUPalletTieHighUpdate Tstring,
          @vSKUDimensionUpdate     TString,
          @vSKUIPCubeUpdate        TString,
          @vSKUIPWeightUpdate      TString,
          @vSKUIPDimensionUpdate   TString;

  /* Table vars for SKUs, SKUValidations and AuditTrail  */
  declare @ttSKUImport       TSKUImportType;
  declare @ttSKUValidations  TImportValidationType;
  declare @ttAuditInfo       TAuditTrailInfo;
begin
  SET NOCOUNT ON;

   if (@RecordId is not null) and (@IsDESameServer = 'Y' /* Yes */)
    insert into #ImportSKUs (
       RecordAction, RecordType, SKU, SKU1, SKU2, SKU3, SKU4, SKU5, Description,
       SKU1Description, SKU2Description, SKU3Description, SKU4Description, SKU5Description,
       AlternateSKU, Status, UoM, InnerPacksPerLPN, UnitsPerInnerPack, UnitsPerLPN,
       InnerPackWeight, InnerPackLength, InnerPackWidth, InnerPackHeight, InnerPackVolume,
       UnitWeight, UnitLength, UnitWidth, UnitHeight, UnitVolume, NestingFactor,
       UnitPrice, UnitCost, PalletTie, PalletHigh,
       PickUoM, ShipUoM, ShipPack, IsSortable, IsConveyable,
       IsScannable, SKUSortOrder, Barcode, UPC, CaseUPC, Brand, ProdCategory, ProdSubCategory,
       PutawayClass, ABCClass, ReturnDisposition, NMFC, HarmonizedCode, Ownership, DefaultCoO, Serialized,
       SKU_UDF1, SKU_UDF2, SKU_UDF3, SKU_UDF4, SKU_UDF5, SKU_UDF6, SKU_UDF7, SKU_UDF8, SKU_UDF9, SKU_UDF10,
       SourceSystem, BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy, HostRecId)
     select RecordAction, RecordType, SKU, SKU1, SKU2, SKU3, SKU4, SKU5, Description,
       SKU1Description, SKU2Description, SKU3Description, SKU4Description, SKU5Description,
       AlternateSKU, Status, UoM, InnerPacksPerLPN, UnitsPerInnerPack, UnitsPerLPN,
       InnerPackWeight, InnerPackLength, InnerPackWidth, InnerPackHeight, InnerPackVolume,
       UnitWeight, UnitLength, UnitWidth, UnitHeight, UnitVolume, NestingFactor,
       UnitPrice, UnitCost, PalletTie, PalletHigh,
       PickUoM, ShipUoM, ShipPack, IsSortable, IsConveyable,
       IsScannable, SKUSortOrder, Barcode, UPC, CaseUPC, Brand, ProdCategory, ProdSubCategory,
       PutawayClass, ABCClass, ReturnDisposition, NMFC, HarmonizedCode, Ownership, DefaultCoO, Serialized,
       SKU_UDF1, SKU_UDF2, SKU_UDF3, SKU_UDF4, SKU_UDF5, SKU_UDF6, SKU_UDF7, SKU_UDF8, SKU_UDF9, SKU_UDF10,
       SourceSystem, BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy, RecordId
    from ##ImportSKUs
    where (RecordId = @RecordId)
  else
  if (@IsDESameServer = 'Y' /* Yes */)
     insert into #ImportSKUs (
       RecordAction, RecordType, SKU, SKU1, SKU2, SKU3, SKU4, SKU5, Description,
       SKU1Description, SKU2Description, SKU3Description, SKU4Description, SKU5Description,
       AlternateSKU, Status, UoM, InnerPacksPerLPN, UnitsPerInnerPack, UnitsPerLPN,
       InnerPackWeight, InnerPackLength, InnerPackWidth, InnerPackHeight, InnerPackVolume,
       UnitWeight, UnitLength, UnitWidth, UnitHeight, UnitVolume, NestingFactor,
       UnitPrice, UnitCost, PalletTie, PalletHigh,
       PickUoM, ShipUoM, ShipPack, IsSortable, IsConveyable,
       IsScannable, SKUSortOrder, Barcode, UPC, CaseUPC, Brand, ProdCategory, ProdSubCategory,
       PutawayClass, ABCClass, ReturnDisposition, NMFC, HarmonizedCode, Ownership, DefaultCoO, Serialized,
       SKU_UDF1, SKU_UDF2, SKU_UDF3, SKU_UDF4, SKU_UDF5, SKU_UDF6, SKU_UDF7, SKU_UDF8, SKU_UDF9, SKU_UDF10,
       SourceSystem, BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy, HostRecId)
     select RecordAction, RecordType, SKU, SKU1, SKU2, SKU3, SKU4, SKU5, Description,
       SKU1Description, SKU2Description, SKU3Description, SKU4Description, SKU5Description,
       AlternateSKU, Status, UoM, InnerPacksPerLPN, UnitsPerInnerPack, UnitsPerLPN,
       InnerPackWeight, InnerPackLength, InnerPackWidth, InnerPackHeight, InnerPackVolume,
       UnitWeight, UnitLength, UnitWidth, UnitHeight, UnitVolume, NestingFactor,
       UnitPrice, UnitCost, PalletTie, PalletHigh,
       PickUoM, ShipUoM, ShipPack, IsSortable, IsConveyable,
       IsScannable, SKUSortOrder, Barcode, UPC, CaseUPC, Brand, ProdCategory, ProdSubCategory,
       PutawayClass, ABCClass, ReturnDisposition, NMFC, HarmonizedCode, Ownership, DefaultCoO, Serialized,
       SKU_UDF1, SKU_UDF2, SKU_UDF3, SKU_UDF4, SKU_UDF5, SKU_UDF6, SKU_UDF7, SKU_UDF8, SKU_UDF9, SKU_UDF10,
       SourceSystem, BusinessUnit, CreatedDate, ModifiedDate, CreatedBy, ModifiedBy, RecordId
       from ##ImportSKUs
  else
  /* Populate the temp table */
  if (@documentHandle is not null)
    begin
      /* insert into SKUImports Table from the xmldata */
      insert into #ImportSKUs (
        InputXML,
        RecordType,
        RecordAction,
        SKU,
        SKU1,
        SKU2,
        SKU3,
        SKU4,
        SKU5,
        Description,
        SKU1Description,
        SKU2Description,
        SKU3Description,
        SKU4Description,
        SKU5Description,
        AlternateSKU,
        Status,
        UoM,
        InnerPacksPerLPN,
        UnitsPerInnerPack,
        UnitsPerLPN,
        InnerPackWeight,
        InnerPackLength,
        InnerPackWidth,
        InnerPackHeight,
        InnerPackVolume,
        UnitWeight,
        UnitLength,
        UnitWidth,
        UnitHeight,
        UnitVolume,
        NestingFactor,
        UnitPrice,
        UnitCost,
        PalletTie,
        PalletHigh,
        PickUoM,
        ShipUoM,
        ShipPack,
        IsSortable,
        IsConveyable,
        IsScannable,
        SKUSortOrder,
        Barcode,
        UPC,
        CaseUPC,
        Brand,
        ProdCategory,
        ProdSubCategory,
        PutawayClass,
        ABCClass,
        ReturnDisposition,
        NMFC,
        HarmonizedCode,
        Ownership,
        DefaultCoO,
        SKU_UDF1,
        SKU_UDF2,
        SKU_UDF3,
        SKU_UDF4,
        SKU_UDF5,
        SKU_UDF6,
        SKU_UDF7,
        SKU_UDF8,
        SKU_UDF9,
        SKU_UDF10,
        SourceSystem,
        BusinessUnit,
        CreatedDate,
        ModifiedDate,
        CreatedBy,
        ModifiedBy,
        HostRecId)
      select
        *
      from OPENXML(@documentHandle, '//msg/msgBody/Record[RecordType/text()="SKU"]', 2) -- condition forces to read only Records with RecordType SKU
      with (InputXML           nvarchar(max)  '@mp:xmltext', -- Directive to return the xmltext of the record node
            RecordType         TRecordType,
            Action             TAction,
            SKU                TSKU,
            SKU1               TSKU                'SKU1/text()',
            SKU2               TSKU                'SKU2/text()',
            SKU3               TSKU                'SKU3/text()',
            SKU4               TSKU                'SKU4/text()',
            SKU5               TSKU                'SKU5/text()',
            Description        TDescription,
            SKU1Description    TDescription,
            SKU2Description    TDescription,
            SKU3Description    TDescription,
            SKU4Description    TDescription,
            SKU5Description    TDescription,
            AlternateSKU       TSKU,
            Status             TStatus,
            UoM                TUoM,
            InnerPacksPerLPN   TInteger,
            UnitsPerInnerPack  TInteger,
            UnitsPerLPN        TInteger,
            InnerPackWeight    TFloat,
            InnerPackLength    TFloat,
            InnerPackWidth     TFloat,
            InnerPackHeight    TFloat,
            InnerPackVolume    TFloat,
            UnitWeight         TFloat,
            UnitLength         TFloat,
            UnitWidth          TFloat,
            UnitHeight         TFloat,
            UnitVolume         TFloat,
            NestingFactor      TFloat,
            UnitPrice          TFloat,
            UnitCost           TFloat,
            PalletTie          TInteger,
            PalletHigh         TInteger,
            PickUoM            TFlags,
            ShipUoM            TFlags,
            ShipPack           TInteger,
            IsSortable         TFlags,
            IsConveyable       TFlags,
            IsScannable        TFlags,
            SKUSortOrder       TDescription,
            Barcode            TBarcode,
            UPC                TUPC,
            CaseUPC            TUPC,
            Brand              TBrand,
            ProdCategory       TCategory,
            ProdSubCategory    TCategory,
            PutawayClass       TCategory,
            ABCClass           TFlag,
            ReturnDisposition  TOperation,
            NMFC               TTypeCode,
            HarmonizedCode     THarmonizedCode,
            Ownership          TOwnership,
            DefaultCoO         TCoO,
            SKU_UDF1           TUDF,
            SKU_UDF2           TUDF,
            SKU_UDF3           TUDF,
            SKU_UDF4           TUDF,
            SKU_UDF5           TUDF,
            SKU_UDF6           TUDF,
            SKU_UDF7           TUDF,
            SKU_UDF8           TUDF,
            SKU_UDF9           TUDF,
            SKU_UDF10          TUDF,
            SourceSystem       TName,
            BusinessUnit       TBusinessUnit,
            CreatedDate        TDateTime                'CreatedDate/text()',
            ModifiedDate       TDateTime                'ModifiedDate/text()',
            CreatedBy          TUserId,
            ModifiedBy         TUserId,
            RecordId           TRecordId);
    end
  else
    begin
      /* insert into SKUImports Table */
      insert into #ImportSKUs (
        RecordAction, RecordType,
        SKU, SKU1, SKU2, SKU3, SKU4, SKU5,
        Description, SKU1Description, SKU2Description,
        SKU3Description, SKU4Description, SKU5Description,
        AlternateSKU, Status, UoM, InnerPacksPerLPN,
        UnitsPerInnerPack, UnitsPerLPN, InnerPackWeight,
        UnitWeight, NestingFactor, UnitPrice, UnitCost, PalletTie, PalletHigh,
        PickUoM, ShipUoM, ShipPack, IsSortable, IsConveyable,
        IsScannable, SKUSortOrder, Barcode, UPC, CaseUPC, Brand, ProdCategory, ProdSubCategory,
        PutawayClass, ABCClass, ReturnDisposition, NMFC, HarmonizedCode, Ownership, DefaultCoO, Serialized,
        SKU_UDF1, SKU_UDF2, SKU_UDF3, SKU_UDF4, SKU_UDF5,
        SKU_UDF6, SKU_UDF7, SKU_UDF8, SKU_UDF9, SKU_UDF10, SourceSystem, BusinessUnit,
        CreatedDate, ModifiedDate, CreatedBy, ModifiedBy, HostRecId)
      select
        @Action, 'SKU',
        @SKU, @SKU1, @SKU2, @SKU3, @SKU4, @SKU5,
        @Description, @SKU1Description, @SKU2Description,
        @SKU3Description, @SKU4Description, @SKU5Description,
        @AlternateSKU, @Status, coalesce(@UoM, 'EA'), @InnerPacksPerLPN,
        @UnitsPerInnerPack, @UnitsPerLPN, @InnerPackWeight,
        @UnitWeight, @NestingFactor, @UnitPrice, @UnitCost, @PalletTie, @PalletHigh,
        @PickUoM, @ShipUoM, @ShipPack, @IsSortable, @IsConveyable,
        @IsScannable, @SKUSortOrder, @Barcode, @UPC, @CaseUPC, @Brand, @ProdCategory, @ProdSubCategory,
        @PutawayClass, @ABCClass, @ReturnDisposition, @NMFC, @HarmonizedCode, @Ownership, @DefaultCoO, @Serialized,
        @UDF1, @UDF2, @UDF3, @UDF4, @UDF5,
        @UDF6, @UDF7, @UDF8, @UDF9, @UDF10, @SourceSystem, @BusinessUnit,
        @CreatedDate, @ModifiedDate, @CreatedBy, @ModifiedBy, @HostRecId;
    end
end /* pr_Imports_SKUs_LoadData */

Go
