/*------------------------------------------------------------------------------
  Copyright (c) Foxfire Technologies (India) Ltd.  All rights reserved

  Revision History:

  Date        Person  Comments

  2020/11/15  MS      Corrections as per New Format (CIMSV3-1210)
  2014/04/16  TK      Changes made to control data using procedure
  2010/09/20  PK      Initial revision.
------------------------------------------------------------------------------*/

Go

/*------------------------------------------------------------------------------*/
/* Countries

See https://countrycode.org/ for the 2 char Country codes. These are important for
internationl shipping

*/
/*------------------------------------------------------------------------------*/
declare @Countries TLookUpsTable, @LookUpCategory TCategory = 'Country';

insert into @Countries
       (LookUpCode, LookUpDescription,                       Status)
values ('AD',       'ANDORRA',                               'A'),
       ('AE',       'UNITED ARAB EMIRATES',                  'A'),
       ('AF',       'AFGHANISTAN',                           'A'),
       ('AG',       'ANTIGUA AND BARBUDA',                   'A'),
       ('AI',       'ANGUILLA',                              'A'),
       ('AL',       'ALBANIA',                               'A'),
       ('AM',       'ARMENIA',                               'A'),
       ('AN',       'NETHERLANDS ANTILLES',                  'A'),
       ('AO',       'ANGOLA',                                'A'),
       ('AQ',       'ANTARCTICA',                            'A'),
       ('AR',       'ARGENTINA',                             'A'),
       ('AS',       'AMERICAN SAMOA',                        'A'),
       ('AT',       'AUSTRIA',                               'A'),
       ('AU',       'AUSTRALIA',                             'A'),
       ('AW',       'ARUBA',                                 'A'),
       ('AX',       'ALAND ISLANDS',                         'A'),
       ('AZ',       'AZERBAIJAN',                            'A'),
       ('BA',       'BOSNIA AND HERZEGOVINA',                'A'),
       ('BB',       'BARBADOS',                              'A'),
       ('BD',       'BANGLADESH',                            'A'),
       ('BE',       'BELGIUM',                               'A'),
       ('BF',       'BURKINA FASO',                          'A'),
       ('BG',       'BULGARIA',                              'A'),
       ('BH',       'BAHRAIN',                               'A'),
       ('BI',       'BURUNDI',                               'A'),
       ('BJ',       'BENIN',                                 'A'),
       ('BM',       'BERMUDA',                               'A'),
       ('BN',       'BRUNEI',                                'A'),
       ('BO',       'BOLIVIA',                               'A'),
       ('BR',       'BRAZIL',                                'A'),
       ('BS',       'BAHAMAS',                               'A'),
       ('BT',       'BHUTAN',                                'A'),
       ('BV',       'BOUVET ISLAND',                         'A'),
       ('BW',       'BOTSWANA',                              'A'),
       ('BY',       'BELARUS',                               'A'),
       ('BZ',       'BELIZE',                                'A'),
       ('CA',       'CANADA',                                'A'),
       ('CC',       'COCOS (KEELING) ISLANDS',               'A'),
       ('CD',       'CONGO, DEMOCRATIC REPUBLIC OF THE',     'A'),
       ('CF',       'CENTRAL AFRICAN REPUBLIC',              'A'),
       ('CG',       'CONGO',                                 'A'),
       ('CH',       'SWITZERLAND',                           'A'),
       ('CI',       'COTE D''IVOIRE',                        'A'),
       ('CK',       'COOK ISLANDS',                          'A'),
       ('CL',       'CHILE',                                 'A'),
       ('CM',       'CAMEROON',                              'A'),
       ('CN',       'CHINA',                                 'A'),
       ('CO',       'COLOMBIA',                              'A'),
       ('CR',       'COSTA RICA',                            'A'),
       ('CU',       'CUBA',                                  'A'),
       ('CV',       'CAPE VERDE',                            'A'),
       ('CX',       'CHRISTMAS ISLAND',                      'A'),
       ('CY',       'CYPRUS',                                'A'),
       ('CZ',       'CZECH REPUBLIC',                        'A'),
       ('DE',       'GERMANY',                               'A'),
       ('DJ',       'DJIBOUTI',                              'A'),
       ('DK',       'DENMARK',                               'A'),
       ('DM',       'DOMINICA',                              'A'),
       ('DO',       'DOMINICAN REPUBLIC',                    'A'),
       ('DZ',       'ALGERIA',                               'A'),
       ('EC',       'ECUADOR',                               'A'),
       ('EE',       'ESTONIA',                               'A'),
       ('EG',       'EGYPT',                                 'A'),
       ('EH',       'WESTERN SAHARA',                        'A'),
       ('ER',       'ERITREA',                               'A'),
       ('ES',       'SPAIN',                                 'A'),
       ('ET',       'ETHIOPIA',                              'A'),
       ('FI',       'FINLAND',                               'A'),
       ('FJ',       'FIJI',                                  'A'),
       ('FK',       'FALKLAND ISLANDS (MALVINAS)',           'A'),
       ('FM',       'MICRONESIA, FEDERATED STATES OF',       'A'),
       ('FO',       'FAROE ISLANDS',                         'A'),
       ('FR',       'FRANCE',                                'A'),
       ('GA',       'GABON',                                 'A'),
       ('GB',       'UNITED KINGDOM',                        'A'),
       ('GD',       'GRENADA',                               'A'),
       ('GE',       'GEORGIA',                               'A'),
       ('GF',       'FRENCH GUIANA',                         'A'),
       ('GG',       'GUERNSEY',                              'A'),
       ('GH',       'GHANA',                                 'A'),
       ('GI',       'GIBRALTAR',                             'A'),
       ('GL',       'GREENLAND',                             'A'),
       ('GM',       'GAMBIA',                                'A'),
       ('GN',       'GUINEA',                                'A'),
       ('GP',       'GUADELOUPE',                            'A'),
       ('GQ',       'EQUATORIAL GUINEA',                     'A'),
       ('GR',       'GREECE',                                'A'),
       ('GS',       'SOUTH GEORGIA/SOUTH SANDWICH ISLANDS',   'A'),
       ('GT',       'GUATEMALA',                             'A'),
       ('GU',       'GUAM',                                  'A'),
       ('GW',       'GUINEA-BISSAU',                         'A'),
       ('GY',       'GUYANA',                                'A'),
       ('HK',       'HONG KONG',                             'A'),
       ('HM',       'HEARD ISLAND AND MCDONALD ISLANDS',     'A'),
       ('HN',       'HONDURAS',                              'A'),
       ('HR',       'CROATIA',                               'A'),
       ('HT',       'HAITI',                                 'A'),
       ('HU',       'HUNGARY',                               'A'),
       ('ID',       'INDONESIA',                             'A'),
       ('IE',       'IRELAND',                               'A'),
       ('IL',       'ISRAEL',                                'A'),
       ('IM',       'ISLE OF MAN',                           'A'),
       ('IN',       'INDIA',                                 'A'),
       ('IO',       'BRITISH INDIAN OCEAN TERRITORY',        'A'),
       ('IQ',       'IRAQ',                                  'A'),
       ('IR',       'IRAN',                                  'A'),
       ('IS',       'ICELAND',                               'A'),
       ('IT',       'ITALY',                                 'A'),
       ('JE',       'JERSEY',                                'A'),
       ('JM',       'JAMAICA',                               'A'),
       ('JO',       'JORDAN',                                'A'),
       ('JP',       'JAPAN',                                 'A'),
       ('KE',       'KENYA',                                 'A'),
       ('KG',       'KYRGYZSTAN',                            'A'),
       ('KH',       'CAMBODIA',                              'A'),
       ('KI',       'KIRIBATI',                              'A'),
       ('KM',       'COMOROS',                               'A'),
       ('KN',       'SAINT KITTS AND NEVIS',                 'A'),
       ('KP',       'NORTH KOREA',                           'A'),
       ('KR',       'SOUTH KOREA',                           'A'),
       ('KW',       'KUWAIT',                                'A'),
       ('KY',       'CAYMAN ISLANDS',                        'A'),
       ('KZ',       'KAZAKHSTAN',                            'A'),
       ('LA',       'LAOS',                                  'A'),
       ('LB',       'LEBANON',                               'A'),
       ('LC',       'SAINT LUCIA',                           'A'),
       ('LI',       'LIECHTENSTEIN',                         'A'),
       ('LK',       'SRI LANKA',                             'A'),
       ('LR',       'LIBERIA',                               'A'),
       ('LS',       'LESOTHO',                               'A'),
       ('LT',       'LITHUANIA',                             'A'),
       ('LU',       'LUXEMBOURG',                            'A'),
       ('LV',       'LATVIA',                                'A'),
       ('LY',       'LIBYA',                                 'A'),
       ('MA',       'MOROCCO',                               'A'),
       ('MC',       'MONACO',                                'A'),
       ('MD',       'MOLDOVA',                               'A'),
       ('ME',       'MONTENEGRO',                            'A'),
       ('MG',       'MADAGASCAR',                            'A'),
       ('MH',       'MARSHALL ISLANDS',                      'A'),
       ('MK',       'MACEDONIA',                             'A'),
       ('ML',       'MALI',                                  'A'),
       ('MM',       'MYANMAR',                               'A'),
       ('MN',       'MONGOLIA',                              'A'),
       ('MO',       'MACAO',                                 'A'),
       ('MP',       'NORTHERN MARIANA ISLANDS',              'A'),
       ('MQ',       'MARTINIQUE',                            'A'),
       ('MR',       'MAURITANIA',                            'A'),
       ('MS',       'MONTSERRAT',                            'A'),
       ('MT',       'MALTA',                                 'A'),
       ('MU',       'MAURITIUS',                             'A'),
       ('MV',       'MALDIVES',                              'A'),
       ('MW',       'MALAWI',                                'A'),
       ('MX',       'MEXICO',                                'A'),
       ('MY',       'MALAYSIA',                              'A'),
       ('MZ',       'MOZAMBIQUE',                            'A'),
       ('NA',       'NAMIBIA',                               'A'),
       ('NC',       'NEW CALEDONIA',                         'A'),
       ('NE',       'NIGER',                                 'A'),
       ('NF',       'NORFOLK ISLAND',                        'A'),
       ('NG',       'NIGERIA',                               'A'),
       ('NI',       'NICARAGUA',                             'A'),
       ('NL',       'NETHERLANDS',                           'A'),
       ('NO',       'NORWAY',                                'A'),
       ('NP',       'NEPAL',                                 'A'),
       ('NR',       'NAURU',                                 'A'),
       ('NU',       'NIUE',                                  'A'),
       ('NZ',       'NEW ZEALAND',                           'A'),
       ('OM',       'OMAN',                                  'A'),
       ('PA',       'PANAMA',                                'A'),
       ('PE',       'PERU',                                  'A'),
       ('PF',       'FRENCH POLYNESIA',                      'A'),
       ('PG',       'PAPUA NEW GUINEA',                      'A'),
       ('PH',       'PHILIPPINES',                           'A'),
       ('PK',       'PAKISTAN',                              'A'),
       ('PL',       'POLAND',                                'A'),
       ('PM',       'SAINT PIERRE AND MIQUELON',             'A'),
       ('PN',       'PITCAIRN',                              'A'),
       ('PR',       'PUERTO RICO',                           'A'),
       ('PS',       'PALESTINIAN TERRITORY, OCCUPIED',       'A'),
       ('PT',       'PORTUGAL',                              'A'),
       ('PW',       'PALAU',                                 'A'),
       ('PY',       'PARAGUAY',                              'A'),
       ('QA',       'QATAR',                                 'A'),
       ('RE',       'REUNION',                               'A'),
       ('RO',       'ROMANIA',                               'A'),
       ('RS',       'SERBIA',                                'A'),
       ('RU',       'RUSSIAN FEDERATION',                    'A'),
       ('RW',       'RWANDA',                                'A'),
       ('SA',       'SAUDI ARABIA',                          'A'),
       ('SB',       'SOLOMON ISLANDS',                       'A'),
       ('SC',       'SEYCHELLES',                            'A'),
       ('SD',       'SUDAN',                                 'A'),
       ('SE',       'SWEDEN',                                'A'),
       ('SG',       'SINGAPORE',                             'A'),
       ('SH',       'SAINT HELENA',                          'A'),
       ('SI',       'SLOVENIA',                              'A'),
       ('SJ',       'SVALBARD AND JAN MAYEN',                'A'),
       ('SK',       'SLOVAKIA',                              'A'),
       ('SL',       'SIERRA LEONE',                          'A'),
       ('SM',       'SAN MARINO',                            'A'),
       ('SN',       'SENEGAL',                               'A'),
       ('SO',       'SOMALIA',                               'A'),
       ('SR',       'SURINAME',                              'A'),
       ('ST',       'SAO TOME AND PRINCIPE',                 'A'),
       ('SV',       'EL SALVADOR',                           'A'),
       ('SY',       'SYRIA',                                 'A'),
       ('SZ',       'SWAZILAND',                             'A'),
       ('TC',       'TURKS AND CAICOS ISLANDS',              'A'),
       ('TD',       'CHAD',                                  'A'),
       ('TF',       'FRENCH SOUTHERN TERRITORIES',           'A'),
       ('TG',       'TOGO',                                  'A'),
       ('TH',       'THAILAND',                              'A'),
       ('TJ',       'TAJIKISTAN',                            'A'),
       ('TK',       'TOKELAU',                               'A'),
       ('TL',       'TIMOR-LESTE',                           'A'),
       ('TM',       'TURKMENISTAN',                          'A'),
       ('TN',       'TUNISIA',                               'A'),
       ('TO',       'TONGA',                                 'A'),
       ('TR',       'TURKEY',                                'A'),
       ('TT',       'TRINIDAD AND TOBAGO',                   'A'),
       ('TV',       'TUVALU',                                'A'),
       ('TW',       'TAIWAN',                                'A'),
       ('TZ',       'TANZANIA',                              'A'),
       ('UA',       'UKRAINE',                               'A'),
       ('UG',       'UGANDA',                                'A'),
       ('UM',       'UNITED STATES MINOR OUTLYING ISLANDS',  'A'),
       ('US',       'UNITED STATES',                         'A'),
       ('UY',       'URUGUAY',                               'A'),
       ('UZ',       'UZBEKISTAN',                            'A'),
       ('VA',       'VATICAN CITY STATE (HOLY SEE)',         'A'),
       ('VC',       'SAINT VINCENT AND THE GRENADINES',      'A'),
       ('VE',       'VENEZUELA',                             'A'),
       ('VG',       'VIRGIN ISLANDS (BRITISH)',              'A'),
       ('VI',       'VIRGIN ISLANDS (U.S.)',                 'A'),
       ('VN',       'VIETNAM',                               'A'),
       ('VU',       'VANUATU',                               'A'),
       ('WF',       'WALLIS AND FUTUNA',                     'A'),
       ('WS',       'SAMOA',                                 'A'),
       ('YE',       'YEMEN',                                 'A'),
       ('YT',       'MAYOTTE',                               'A'),
       ('YU',       'YUGOSLAVIA',                            'A'),
       ('ZA',       'SOUTH AFRICA',                          'A'),
       ('ZM',       'ZAMBIA',                                'A'),
       ('ZW',       'ZIMBABWE',                              'A')

exec pr_LookUps_Setup @LookUpCategory, @Countries, @LookUpCategoryDesc = 'Country';

Go
